import { Plus_Jakarta_Sans, Caveat, Geist } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const plusJakartaSans = Plus_Jakarta_Sans({
    variable: "--font-plus-jakarta-sans",
    subsets: ["latin"],
});

const caveat = Caveat({
    variable: "--font-caveat",
    subsets: ["latin"],
});

const geist = Geist({
    variable: "--font-geist",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${plusJakartaSans.variable} ${caveat.variable} ${geist.variable} font-plus-jakarta-sans text-slate-950 antialiased`}
            >
                <Navbar />
                {children}
            </body>
        </html>
    );
}
